language: node_js

node_js:
  - 14

before_install: |
  cat << EOF > ~/.npmrc
  //npm.pkg.github.com/:_authToken=${GITHUB_PERSONAL_ACCESS_TOKEN}
  @smartsupp:registry=https://npm.pkg.github.com
  EOF

script:
  - ./scripts/build.sh

deploy:
  provider: script
  script: ./scripts/docs-deploy.sh
  skip_cleanup: true
  on:
    branch: *
