language: node_js
node_js:
  - 12
install:
  - npm install
cache:
  directories:
    - "$HOME/.npm"
script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run docs:build
deploy:
  provider: script
  script: ./scripts/docs-deploy.sh
  skip_cleanup: true
  on:
    branch: '*'
