language: node_js

node_js:
  - "16.13"

before_install: |
  cat << EOF > ~/.npmrc
  //npm.pkg.github.com/:_authToken=${GITHUB_PERSONAL_ACCESS_TOKEN}
  @smartsupp:registry=https://npm.pkg.github.com
  EOF

script:
  - ./scripts/build.sh

deploy:
  provider: pages
  local_dir: docs/.vuepress/dist
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  on:
    branch: master
